
export enum CatnipCompilerStage {
    SB3_IR0_PREPASS,
    SB3_IR0_GEN,
    
    IR0_IR1_PREPASS,
    IR0_IR1_GEN,

    IR1_WASM_PREPASS,
    IR1_WASM_GEN,

    MODULE_PREWRITE,
    MODULE_WRITE,
    MODULE_BINARYEN_OPTIMIZE,
    MODULE_INSTANTIATE,
}
